In [3]:
import cvxpy as cv
import numpy as np
import matplotlib

In [4]:
#define Variables and constraints
n=4
x=cv.Variable((4,4))
c=np.array([[0,2,1,0],[2,0,1,1],[1,1,0,1],[0,1,1,0]])
constraints=[x>=0,x+cv.transpose(x)<=c,cv.sum(x[1:n-1,:],axis=1)==cv.sum(cv.transpose(x)[1:n-1,:],axis=1),cv.sum(x[:,0])==0,cv.sum(x[n-1,:])==0]

In [6]:
#objective function
objective=cv.Maximize(cv.sum(x[0,:]))

In [7]:
problem=cv.Problem(objective,constraints)

In [8]:
print("maxflow",problem.solve())
print("optimizer =",x.value)

maxflow 2.000000000035156
optimizer = [[-1.11794888e-11  1.34157340e+00  6.58426602e-01  1.04779154e-11]
 [-8.64689711e-12  8.94734019e-14  5.02588193e-01  1.00000000e+00]
 [ 2.57433729e-11  1.61014795e-01  8.94734019e-14  1.00000000e+00]
 [-5.93137097e-12  5.87824662e-12 -5.68616735e-12  5.75960182e-12]]
